trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    pip install awscli
  displayName: 'Install AWS CLI'

# - script: |
#     aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
#     aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
#     aws configure set default.region $(AWS_DEFAULT_REGION)
#   displayName: 'Configure AWS CLI'

# - script: |
#     aws s3api create-bucket --bucket $(BUCKET_NAME) --region $(AWS_DEFAULT_REGION) --create-bucket-configuration LocationConstraint=$(AWS_DEFAULT_REGION)
#   displayName: 'Create S3 Bucket'

